[changelog]
header = ""
body = """
{% if version -%}
## [{{ version | split(pat="-v") | last }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits -%}
- {% if commit.scope %}(**{{ commit.scope }}**) {% endif %}\
{% if commit.breaking %}[**BREAKING**] {% endif %}\
{{ commit.message | upper_first }}\
{% if commit.links %} ([{{ commit.links | map(attribute="text") | join(sep=", ") }}]({{ commit.links | first | get(key="href") }})){% endif %}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/accelmars/resolver-env/pull/$1" },
]
commit_parsers = [
    { message = "^chore: release", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^feat!|^fix!|^refactor!|^perf!", group = "<!-- 0 -->Breaking Changes" },
    { message = "^feat", group = "<!-- 1 -->Features" },
    { message = "^fix", group = "<!-- 2 -->Bug Fixes" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^refactor", group = "<!-- 4 -->Refactor" },
    { message = "^doc", group = "<!-- 5 -->Documentation" },
    { message = "^test", skip = true },
    { message = "^chore|^ci|^build", skip = true },
    { message = "^style", skip = true },
    { message = "^wip", skip = true },
]
protect_breaking_commits = true
filter_commits = true
tag_pattern = "accelmars-resolver-env-v[0-9]*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "newest"
